[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://tabela-fipe-celulares-api.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173